clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: 'Library-Master.Desktop\Library-Master.Desktop.csproj'
  version: '0.0.{build}'
before_build:
  - ps: dotnet --info
  - ps: nuget restore -verbosity quiet
  - ps: dotnet tool restore
  - ps: dotnet ef database update --project Library-Master.EntityFramework\
build:
  project: Library-Master.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true