// <auto-generated />
using System;
using Library_Master.Desktop.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Library_Master.Desktop.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20210110093951_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Library_Master.Desktop.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Antolin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutorKuerzel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Besonderheit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezugsquelle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Entliehen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErscheinungsJahr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fach")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HinzufuegeDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Informationen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategorie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Klasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nummer")
                        .HasColumnType("TEXT");

                    b.Property<double>("Preis")
                        .HasColumnType("REAL");

                    b.Property<int?>("QrCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sparte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Verlag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ZuletztEntliehen")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZuletztEntliehenVon")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("QrCodeId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Library_Master.Desktop.Entities.QrCode", b =>
                {
                    b.Property<int>("QrCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Besonderheit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kuerzel")
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCodeString")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .HasColumnType("TEXT");

                    b.HasKey("QrCodeId");

                    b.ToTable("QrCode");
                });

            modelBuilder.Entity("Library_Master.Desktop.Entities.Book", b =>
                {
                    b.HasOne("Library_Master.Desktop.Entities.QrCode", "QrCode")
                        .WithMany()
                        .HasForeignKey("QrCodeId");

                    b.Navigation("QrCode");
                });
#pragma warning restore 612, 618
        }
    }
}
